Feature/task 1042 add maximum time to the states of a state machine
virtualsatellite/VirtualSatellite4-Core pull request #1043
Opened 2022-01-07 10:27 UTC by maurpa

Closes #1042  Added maximum time to State as FloatProperty
![image](https://user-images.githubusercontent.com/75322624/148530445-2222c441-381e-4fd6-9fab-8f4724b56e8b.png)

2022-01-07 15:43 UTC, GeorgeNasrDLR commented on de.dlr.sc.virsat.model.extension.statemachines/concept/concept.xmi
> +    <properties xsi:type="dvlm_cppd:FloatProperty" name="maxTime" description="The maximum time spend in the state" quantityKindName="Time" unitName="Second" defaultValue="0.0"/>
minor thing: time spent*

2022-01-07 15:47 UTC, GeorgeNasrDLR requested changes
Just this minor change ;)

2022-01-10 12:13 UTC, GeorgeNasrDLR approved these changes

2022-01-11 14:07 UTC, SaMuellerDLR approved these changes
Approved!

2022-01-11 14:07 UTC, merged