Task #1196 - Use the provided query parameter name when creating a SEI
virtualsatellite/VirtualSatellite4-Core pull request #1197
Opened 2024-08-12 08:18 UTC by dellerDLR

Currently the post route of the SEi resource does not consider the name query parameter (eventhough its states in the OpenAPI spec).
Furthermore the type property in the response was wrongly set, which is also fixed.

2024-08-12 09:58 UTC, kain-ap approved these changes
Looks fine to me :)

2024-08-15 07:03 UTC, franzTobiasDLR approved these changes

2024-10-08 10:49 UTC, PhilMFischer requested changes

2024-10-08 10:49 UTC, PhilMFischer commented on de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/ModelAccessResource.java
> +	public static final List<?> RESOURCE_CLASSES = Arrays.asList(RepoModelAccessResource.class,
Please no use of autoformaters corrupting all layout of the code.

2024-12-04 08:24 UTC, dellerDLR commented
Already done in #1237

2024-12-04 08:24 UTC, closed without merging