QUDV Icon adapted
virtualsatellite/VirtualSatellite4-Core pull request #1220
Opened 2024-10-22 10:40 UTC by fmbouga

2024-10-23 10:33 UTC, PhilMFischer requested changes
Please have a look to the comments. we can also work on the icon next week.

2024-10-23 10:33 UTC, PhilMFischer commented on de.dlr.sc.virsat.qudv.ui/resources/facets-page-wizban.png
Hi @fmbouga I think we should have an icon in the style we usually have in virtual satellite. Even though it is a nice icon i think it does not tell anything about QUDV or units in general. Maybe we should brainstorm a bit together.

2024-10-23 10:33 UTC, PhilMFischer commented on .mailmap
Looks like there is a merge conflict that still needs to be resolved.

2024-10-23 10:33 UTC, PhilMFischer commented on known_authors.txt
> +mbou_fr
your GitHub account name should be added here.

2024-10-23 10:34 UTC, PhilMFischer commented
Please also add a description telling us what this PR is about.

2024-10-23 11:46 UTC, fmbouga commented
@PhilMFischer alright thanks. Yeah it is true the Icon was like trying to show some symbols, quantity and unit all together. Next week we could then either generate it together with Copilot or find another way. Thanks for the other comments related to Known authors, description

2024-11-04 10:25 UTC, PhilMFischer commented
Decided to completely remove the icon from the editor, since it created issues when rendering.

2024-11-04 10:30 UTC, PhilMFischer approved these changes
Looks great now- good idea to remove the icon.

2024-11-04 11:25 UTC, kain-ap approved these changes

2024-11-14 14:07 UTC, merged

2024-11-14 14:07 UTC, PhilMFischer commented
Closes #29