Add concept projects for an empty mechanical project - (Task #155)
virtualsatellite/VirtualSatellite4-Core pull request #158
Opened 2019-07-22 13:10 UTC by franzTobiasDLR

2019-07-22 13:21 UTC, SaMuellerDLR requested changes

2019-07-22 13:21 UTC, SaMuellerDLR commented on de.dlr.sc.virsat.model.extension.mechanical/concept/concept.concept
> +Concept de.dlr.sc.virsat.model.extension.mechanical description "Concept for mechanical engineering" version 0.1
Style thingy. it should be `Concept de.dlr.sc.virsat.model.extension.mechanical description "Concept for mechanical engineering" version 0.1 {` with the `{` on the same line.

2019-07-22 13:21 UTC, SaMuellerDLR commented on de.dlr.sc.virsat.model.extension.mechanical/concept/concept.concept
> +{
Also the concept should have the header 

`/*******************************************************************************
 * Copyright (c) 2008-2019 German Aerospace Center (DLR), Simulation and Software Technology, Germany.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
*******************************************************************************/`

like the other concepts.

2019-07-22 13:39 UTC, SaMuellerDLR submitted a review, later dismissed
Approved!

2019-07-22 15:03 UTC, andriikovalov-dlr submitted a review, later dismissed

2019-07-23 06:35 UTC, SaMuellerDLR approved these changes
Approved!

2019-07-23 07:47 UTC, andriikovalov-dlr approved these changes

2019-07-23 07:47 UTC, merged