Improveme RepoManagementController
virtualsatellite/VirtualSatellite4-Core pull request #730
Opened 2020-08-28 11:08 UTC by JAmmermann-DLR

This PR fixes the handling of the .properties file.

- in ServerRepoHelper:
  - registering a repository (project) now creates the .properties file
  - deleting also deletes the files
  - updating also saves the updated file
-  add test cases in ServerRepoHelper
- add test for removing a project in ServerRepositoryTest and minor fix in ServerRepository
- minor improvements in RepoManagementController and ProjectManagementResource

Closes https://github.com/virtualsatellite/VirtualSatellite4-Core/issues/556

2020-08-28 11:10 UTC, JAmmermann-DLR commented
I noticed we still don't checkout/remove a repository at runtime when using the management REST API. I think have to add this to the ServerRepoHelper logic, do you agree? I would create a new ticket for this.

2020-09-04 09:05 UTC, andriikovalov-dlr requested changes
Looks good, just one minor point

2020-09-04 09:05 UTC, andriikovalov-dlr commented on de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/repository/ServerRepoHelperTest.java
> +	Path configFilePath;
private?

2020-09-09 14:07 UTC, SaMuellerDLR approved these changes
Looking clean!

2020-09-14 14:09 UTC, andriikovalov-dlr approved these changes

2020-09-14 14:10 UTC, merged