Added version number to existing REST APIs
virtualsatellite/VirtualSatellite4-Core pull request #801
Opened 2020-10-29 12:06 UTC by JAmmermann-DLR

Now the APIs follow the URL pattern of _http://localhost:port/rest/[API]/[VERSION]/... _.

Each Servlet now has its own name and version number, that is registered in the `VirSatJettyServer`

Fixed the API paths in the test cases

2020-10-29 15:12 UTC, SaMuellerDLR approved these changes
Approved!

2020-11-04 10:51 UTC, PhilMFischer requested changes
At least i would like to see, that we have a follow on ticket, to activate authentication for the upcoming release. At minimum user/password by file configuration should be turned on as standard.

2020-11-05 08:23 UTC, JAmmermann-DLR commented
> 
> 
> At least i would like to see, that we have a follow on ticket, to activate authentication for the upcoming release. At minimum user/password by file configuration should be turned on as standard.

Created follow up ticket https://github.com/virtualsatellite/VirtualSatellite4-Core/issues/812

2020-11-16 10:58 UTC, PhilMFischer approved these changes

2020-11-16 10:58 UTC, merged