Updated state machine concept - (Task #818)
virtualsatellite/VirtualSatellite4-Core pull request #819
Opened 2020-11-06 11:09 UTC by SaMuellerDLR

- Added simple detail description field for states
- Added simple trigger field for transitions

Closes #818

---
Task #818: Extend state machines concept with additional properties

2020-11-09 08:19 UTC, franzTobiasDLR approved these changes

2020-11-10 09:30 UTC, PhilMFischer requested changes
I think we should reconsider the change to the concept to improve to enhance the semantics.

2020-11-10 09:30 UTC, PhilMFischer commented on de.dlr.sc.virsat.model.extension.statemachines/concept/concept.concept
> +		Reference trigger of Type GenericCategory description "The event that triggers the Transition";
SHould a trigger be of type generic? I think we are sacrifying some semantics for the sake of simplicity. I think we should at least provide a simple Category such as a generic Event or Trigger that can be referenced and used in other Concepts.

2020-11-10 13:01 UTC, PhilMFischer requested changes
I think loading the labelprovider from the platform registry should be reviewed and most likely be improved.

2020-11-10 15:29 UTC, PhilMFischer approved these changes

2020-11-10 21:44 UTC, merged