Add manual section for requirements
virtualsatellite/VirtualSatellite4-Core pull request #861
Opened 2020-12-01 00:01 UTC by franzTobiasDLR

Port old requirements manual to core manual and update it to latest state of the requirements concept.

Closing #852

2020-12-02 10:37 UTC, PhilMFischer approved these changes

2020-12-02 10:38 UTC, PhilMFischer commented on de.dlr.sc.virsat.docs.feature/src/docs/VirSat_Core_User_Manual.adoc
> +Add a RequirementsConfiguration under the collection
ALready fixed it

2020-12-04 11:37 UTC, franzTobiasDLR commented on de.dlr.sc.virsat.docs.feature/src/docs/VirSat_Core_User_Manual.adoc
> +To support model based requirements management and to verify requirements by using the system model, Virtual Satellite provides a concept to model requirements. Requirements can be either imported fr
There is now semantic-less tracing of requirements to the system model, only tracing as aprt of verification. For that we have a section in the chapter.

2020-12-04 12:25 UTC, SaMuellerDLR commented
@franzTobiasDLR @franzTobiasDLR Its showing me the entire document as a diff, whats going on here? :D

2020-12-04 12:28 UTC, franzTobiasDLR commented
Guess there is some line ending stuff going on... 😒

2020-12-04 12:35 UTC, franzTobiasDLR commented
@SaMuellerDLR Fixed.

2020-12-04 13:19 UTC, SaMuellerDLR requested changes
Great work. Comments are just some minor editorial improvements.

2020-12-04 13:19 UTC, SaMuellerDLR commented on de.dlr.sc.virsat.docs.feature/src/docs/VirSat_Core_User_Manual.adoc
> +To integrate requirements management into the model-based systems engineering process, Virtual Satellite supports import of requirements from external tools.
```suggestion
To integrate requirements management into the model-based systems engineering process, Virtual Satellite supports importing requirements from external tools.

```

2020-12-04 13:19 UTC, SaMuellerDLR commented on de.dlr.sc.virsat.docs.feature/src/docs/VirSat_Core_User_Manual.adoc
> +The left part of the dialog allows to filter by the container element of the configuration, the right side show all applicable types in the currently selected tree element.
```suggestion
The left part of the dialog allows to filter by the container element of the configuration, the right side shows all applicable types in the currently selected tree element.

```

2020-12-04 13:19 UTC, SaMuellerDLR commented on de.dlr.sc.virsat.docs.feature/src/docs/VirSat_Core_User_Manual.adoc
> +Depending on the used concepts in the project there might be different of these model-based verification methods.
```suggestion
Depending on the used concepts in the project, there might be different model-based verification methods. 

```

2020-12-04 15:04 UTC, SaMuellerDLR approved these changes
Approved!

2020-12-04 15:04 UTC, merged