Added Swagger Annotations and a Documentation Resource
virtualsatellite/VirtualSatellite4-Core pull request #908
Opened 2021-01-11 12:51 UTC by JAmmermann-DLR

- Added documentation via annotating the bean classes
- Updated the server pom to now create seperate documentation for the Model and Management API
- Generated the swagger documentation into doc-gen directory
- Update docs feature:
  - Added dependency to server
  - Added section for model inheritance
  - Added generated documentation
- Added a DocumetationResource that serves the swagger.json/.yaml via the Rest API

So we should be able to deploy a complete server documentation after this PR :)

There are less changes here than git says, because I added a lot of generated files and it doesn't show the right changes for some bean files :)

Closes #834

2021-01-19 12:00 UTC, SaMuellerDLR requested changes
Great work, only super minor comments!

2021-01-20 12:26 UTC, JAmmermann-DLR commented on de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/DocumentationResource.java
> +			e.printStackTrace();
No I will change it

2021-01-20 12:40 UTC, JAmmermann-DLR commented on de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/servlet/RepoManagementServlet.java
> +			final AbstractBinder docBinder = new AbstractBinder() {
This seems to only work on interfaces and not on abstract classes (Compiler Error: "The target type of this expression must be a functional interface")

2021-01-20 12:55 UTC, SaMuellerDLR approved these changes
Approved!

2021-01-25 10:08 UTC, andriikovalov-dlr approved these changes

2021-01-25 10:08 UTC, merged