Gitignored swagger doc
virtualsatellite/VirtualSatellite4-Core pull request #954
Opened 2021-02-26 11:59 UTC by JAmmermann-DLR

- Added gitignore to swagger doc output folders
- Removed generated swagger docs from version control
- Removed position attributes from swagger annotations
- Minor improvements in the documentation
- Added jersey test framework to external lib (had to manually exclude junit and hamcrest dependencies)
- Refactored documentation resource (now mocked with the jersey test fw)
- Increased heap size of run configuration

2021-02-26 12:10 UTC, maurpa approved these changes

2021-03-02 14:42 UTC, SaMuellerDLR requested changes
Nice work. Only super tiny thing.

2021-03-02 14:42 UTC, SaMuellerDLR commented on de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/test/AJerseyTest.java
> +		enable(TestProperties.LOG_TRAFFIC);
Some weird whitespacing here.

2021-03-03 08:17 UTC, JAmmermann-DLR commented on de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/test/AJerseyTest.java
> +		enable(TestProperties.LOG_TRAFFIC);
Thanks, changed!

2021-03-04 08:25 UTC, SaMuellerDLR approved these changes
Approved!

2021-03-04 08:25 UTC, merged