Added create endpoints
virtualsatellite/VirtualSatellite4-Core pull request #984
Opened 2021-04-26 07:21 UTC by JAmmermann-DLR

Added three create endpoints and test cases for:
- RootSei in ModelAccessResource
- Sei in StructuralElementInstanceResource
- Ca in CategoryAssignmentResource

Also added some minor improvement in the server errors.

@SaMuellerDLR the only think we don't handle at the moment are composed beans. For example what if one wants to create a ca inside a composed bean?

Closes #964

2021-05-04 13:34 UTC, SaMuellerDLR requested changes
Great job as usual. I got some minor comments where I believe that there is too much logic in the server that should be in a model plugin and just get called from the server classes.

2021-05-04 13:34 UTC, SaMuellerDLR commented on de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/ModelAccessResource.java
> +		StructuralElement se = ActiveConceptHelper.getStructuralElement(concept, fullQualifiedName.substring(idx + 1));
I feel like the logic of geting the StructuralElement for an FQN should be part of the ActiveConceptHelper so we don't have those details in the server logic.

2021-05-04 13:34 UTC, SaMuellerDLR commented on de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/modelaccess/CategoryAssignmentResource.java
> +			CategoryAssignment newCa = CategoriesFactory.eINSTANCE.createCategoryAssignment();
Maybe a minor simplification is possible using the CategoryInstantiator. What is the current default name of the instantiated category assignment? Null?

2021-05-04 13:34 UTC, SaMuellerDLR commented on de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/ModelAccessResource.java
> +		StructuralElementInstance newSei = StructuralFactory.eINSTANCE.createStructuralElementInstance();
StructuralInstantiator could be used here to simplify instantiation logic (creating sei + setting type + setting default name)

2021-05-05 12:41 UTC, maurpa approved these changes

2021-05-11 09:37 UTC, JAmmermann-DLR commented
Falsely closed via #985

2021-05-18 16:33 UTC, SaMuellerDLR approved these changes
Approved!

2021-05-18 16:33 UTC, merged